"""Status report (markdown) generated from the catalog: what works, with which fixes, and PC VR alternatives."""
from __future__ import annotations

import time
from pathlib import Path

from .recommend import catalog

LABEL = {"works": "Works", "issues": "Works with issues", "unsupported": "Does not work on the Frame",
         "unknown": "Untested"}


def render() -> str:
    entries = sorted(catalog.load().values(), key=lambda e: e.title.lower())
    by = {k: [e for e in entries if e.status == k] for k in LABEL}
    out = ["# Steam Frame conversions: status", "",
           f"Generated by FramePort from its catalog on {time.strftime('%Y-%m-%d')}. "
           f"**{len(by['works'])} work · {len(by['issues'])} work with issues · "
           f"{len(by['unsupported'])} do not work**", ""]
    for k in ("works", "issues", "unsupported"):
        if not by[k]:
            continue
        out += [f"## {LABEL[k]} ({len(by[k])})", ""]
        for e in by[k]:
            fixes = ", ".join(e.frame + [f"{a}={v}" for a, v in e.adapter.items()] + e.overport_extra
                              + (["alt build: " + ", ".join(e.alt_overport)] if e.alt_overport else []))
            line = f"- **{e.title}** (`{e.package}` {e.tested_version})"
            if e.notes:
                line += f": {e.notes}"
            if fixes:
                line += f" _Fixes: {fixes}._"
            if e.pcvr_alternative:
                line += f" PC VR: {e.pcvr_alternative}"
            out.append(line)
        out.append("")
    out += ["All games also get the overport defaults and the automatic Frame fixes (FrameBridge adapter, launcher "
            "category, platform stubs/compat, telemetry stubs) when they need them. See docs/PLAYBOOK.md in "
            "FramePort.", ""]
    return "\n".join(out)


def write(path: Path) -> Path:
    path.write_text(render(), encoding="utf-8")
    return path
